sudo: required

services:
  - docker

before_install:
  - docker build --tag smonn/react-test --file ./client/Dockerfile.dev ./client

script:
  - docker run --env CI=true smonn/react-test yarn test

after_success:
  - docker build --tag smonn/multi-client ./client
  - docker build --tag smonn/multi-nginx ./nginx
  - docker build --tag smonn/multi-server ./server
  - docker build --tag smonn/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push smonn/multi-client
  - docker push smonn/multi-nginx
  - docker push smonn/multi-server
  - docker push smonn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-259347196174
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
